# Generated by Django 5.2.6 on 2026-07-20 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_schedule_appointment_token_number'),
        ('queues', '0002_alter_queue_options_alter_queue_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queue',
            options={},
        ),
        migrations.RenameField(
            model_name='queue',
            old_name='queue_number',
            new_name='token_number',
        ),
        migrations.AlterField(
            model_name='queue',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entry', to='appointments.appointment'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='waiting', max_length=20),
        ),
    ]
