# Generated by Django 5.2.6 on 2026-07-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0003_alter_queue_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='token_number',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
