# Generated by Django 5.2.6 on 2026-07-28 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0004_alter_queue_token_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='token_number',
            field=models.PositiveIntegerField(),
        ),
    ]
