# Generated by Django 5.2.6 on 2026-07-27 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_clinic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='clinic',
        ),
    ]
