# Generated by Django 5.2.6 on 2026-07-27 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_clinic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dev_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
