# Generated by Django 5.2.6 on 2026-07-27 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_schedule_appointment_token_number'),
        ('clinics', '0002_alter_clinic_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clinics.clinic'),
        ),
    ]
