# Generated by Django 5.2.6 on 2026-07-27 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinic',
            options={'ordering': ['id']},
        ),
    ]
