# Generated by Django 5.2.6 on 2026-07-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctor_clinic'),
        ('schedules', '0002_alter_doctorschedule_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorschedule',
            options={'ordering': ['doctor', 'day', 'start_time']},
        ),
        migrations.AddConstraint(
            model_name='doctorschedule',
            constraint=models.UniqueConstraint(fields=('doctor', 'day', 'start_time'), name='unique_schedule_per_doctor'),
        ),
    ]
